namespace BetterClearTypeTuner.Native
{
	/// <summary>
	/// Subset of SPI_* values used for font smoothing via SystemParametersInfo.
	/// </summary>
	public enum SPI : uint
	{
		SPI_GETFONTSMOOTHING = 0x004A,
		SPI_SETFONTSMOOTHING = 0x004B,
		SPI_GETFONTSMOOTHINGTYPE = 0x200A,
		SPI_SETFONTSMOOTHINGTYPE = 0x200B,
		SPI_GETFONTSMOOTHINGCONTRAST = 0x200C,
		SPI_SETFONTSMOOTHINGCONTRAST = 0x200D,
		SPI_GETFONTSMOOTHINGORIENTATION = 0x2012,
		SPI_SETFONTSMOOTHINGORIENTATION = 0x2013,
	}
}
